[package]
name = "evi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
unicode-width = "0.1.11"
log = "0.4.20"
log4rs = "1.3.0"
