name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  e2e:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r e2e/requirements.txt
    - name: Build evi binary
      run: cargo build --verbose
    - name: Run e2e tests
      run: |
        pytest e2e --verbose
      env:
        EVI_DELAY_BEFORE_SEND: '0.1'
        EVI_DELAY_AFTER_ESC: '0.1'
        EVI_PEXPECT_TIMEOUT: '0.5'
